config/routes.rb
Rails.application.routes.draw do
  root 'offers#index'
  resources :offers
  resources :measures
  resources :comments
  resources :locations
  resources :products
  devise_for :users
  resources :users, :except => [:edit]
  match 'comments/send_mail', to: 'comments#send_mail', via: 'post'
  get  "offers/download", to: "offers#download"
  post  "offers/extend", to: "offers#extend", as: "extend"
  post "offers/create_offer_user", to: "offers#create_offer_user", as: "create_offer_user"
  post "offers/change_status" => "offers#change_status"
  post "users/create_user", to: "users#create_user", as: "create_user"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	after_initialize :init
	# relation
	belongs_to :user
	belongs_to :offer
	
	def init
		self.status  ||= 1
	end
	
	# default for will_paginate
  	self.per_page = 10
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  	@comments = Comment.all.order('created_at desc').page(params[:page])
  end
  def show
  	@comment = Comment.find(params[:id])
  	@comment.update(:status => 2)
  end
  
  def create
    @comment = Comment.new(comments_params)
    respond_to do |format|
      if @comment.save
      	@offer = Offer.find(@comment.offer_id)
        flash[:notice] = 'Su mensaje ha sido enviado'
        format.html { redirect_to @offer}
        format.json { render :show, status: :created, location: @location }
        format.js {}
      else
      	flash[:notice] = 'Se ha producido un error'
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end
  
  def send_mail
    email = params[:email]
    body = params[:comments]
    @comment = Comment.find(params[:id])
    NotificationMailer.contact_email( email, body).deliver
    redirect_to @comment, notice: 'Envio de mensaje'
  end

  private
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def comments_params
      params.require(:comment).permit(:offer_id, :user_id, :description, :subject)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.slim
.errors
= form_for @comment do |f|
    = f.label :Asunto
    = f.text_field :subject, :class =>"form-control"
    br
    = f.label :commentario
    = f.text_field :description, :class =>"form-control"
    br
    = f.hidden_field :offer_id, :value =>params[:id],  :class =>"form-control"
    = f.hidden_field :user_id, :value => current_user.id ,:class =>"form-control"
    =f.submit :class =>"btn btn-primary btn-block"

app/views/comments/index.html.erb
<div class="page-header">
<ol class="breadcrumb">
    <li class="active">
        <i style="margin-right: 10px;" class="fa fa-envelope-o"></i>Commentarios
    </li>

</ol>
</div>
<div class="row">
    <div class="col-lg-3 valign-top">
        <!-- panel body -->
        <div class="panel-body" style="padding: 0px;">
            <!-- Browse -->
            <h5 class="semibold">Principal</h5>
            <div class="list-group">
                <a class="list-group-item" href=""><i class="fa fa-inbox"></i> Recibidos <span class="semibold text-muted pull-right"><%= @comments.count%></span></a>
            </div>
        </div>
        <hr>
        <!--/ panel body -->
    </div>
    <div class="col-lg-9">
        <!-- panel body -->
        <div class="panel-body">
            <!-- email list -->
            <div class="table-responsive nm">
                <table id="table-email" class="table table-striped table-hover table-email">
                    <tbody>
                        <% @comments.each do |comment|%>
                            <tr class="commentario">
                                <td>
                                    <input type="checkbox" data-target="tr" data-toggle="selectrow" value="1" id="customcheckbox1">  
                                </td>
                                <td class="meta">
                                    <h5 class="sender"><%= comment.user.name%></h5>
                                    <p class="date"><%= comment.created_at.strftime("%m/%d/%Y")%></p>
                                </td>
                                <td class="message">
                                    <h5 class="heading">
                                        <i class="ico-square text-danger mr5"></i> 
                                        <i class="ico-attachment text-muted mr5"></i>
                                        <a href="<%= comment_path(comment)%>"><%= comment.subject%></a>
                                        <%if comment.status == 1%>     
                                            <span class="label label-info" style="margin-top: 10p2x;">Nuevo</span>
                                        <%end%>
                                    </h5><br><br>
                                    <p class="text" style="float: left;"><%= comment.description%></p>
                                </td>
                            </tr>
                        <%end%>
                    </tbody>
                </table>
                <%= will_paginate @comments, :locals => { :comments => @comments }, renderer: BootstrapPagination::Rails%>
            </div>
                <!--/ email list -->
        </div>
    </div>
        <!--/ panel body -->
</div>

app/views/comments/show.html.erb
<div class="page-header">
<ol class="breadcrumb">
    <li class="active">
        <i style="margin-right: 10px;" class="fa fa-envelope-o"></i>Correo de <%= @comment.user.name%>
    </li>
</ol>
</div>
<div class="row">
    <div class="col-lg-3 valign-top">
        <!-- panel body -->
        <div class="panel-body" style="padding: 0px;">
            <!-- Browse -->
            <h5 class="semibold">Principal</h5>
            <div class="list-group">
                <a class="list-group-item" href="<%= comments_path%>"><i class="fa fa-inbox"></i> Recibidos <span class="semibold text-muted pull-right"><%= Comment.all.count%></span></a>
            </div>
        </div>
        <hr>
        <!--/ panel body -->
    </div>
    <div class="col-lg-9">
        <!-- panel body -->
        <div class="panel-body">
            <!-- email list -->
            <div class="table-responsive nm">
                <div class="wrapper">
                    <h4 class="m-b-15 m-t-0 p-b-10 underline"><%= @comment.subject.upcase%></h4>
                    <hr>
                    <ul class="media-list underline m-b-20 p-b-15">
                        <li class="media media-sm clearfix">
                            <div class="media-body">
                                <span class="email-from text-inverse f-w-600">
                                   <strong>De:</strong>  <%= @comment.user.email%>
                                </span>
                                <span class="text-muted m-l-5 pull-right"><i class="fa fa-clock-o fa-fw"></i> <%= @comment.created_at.to_formatted_s(:short)%></span>
                                <br>
                            </div>
                        </li>
                    </ul>
                    <p class="f-s-12 text-inverse"> 
                        <br>
                            <%= @comment.description%>
                        <br>
                    </p>
                    --
                    <p class="f-s-12 text-inverse"><%= @comment.user.name%></p>
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                        Responder
                    </button>
                </div>
            </div>
                <!--/ email list -->
        </div>
    </div>
        <!--/ panel body -->
</div>
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Responder</h4>
      </div>
      <div class="modal-body">
        <%= form_tag(comments_send_mail_path) do %>
            <label for="input4">Mensaje </label>
            <%= hidden_field_tag 'email',   @comment.user.email%>
            <%= hidden_field_tag 'id',   @comment.id%>
            <%= text_area_tag 'comments', nil, class: 'form-control', rows: 4%>
            <br>
            <%= submit_tag "Enviar" %>
        <%end%>
      </div>
    <div>
</div>