config/routes.rb
Rails.application.routes.draw do
  root 'offers#index'
  resources :offers
  resources :measures
  resources :comments
  resources :locations
  resources :products
  devise_for :users
  resources :users, :except => [:edit]
  match 'comments/send_mail', to: 'comments#send_mail', via: 'post'
  get  "offers/download", to: "offers#download"
  post  "offers/extend", to: "offers#extend", as: "extend"
  post "offers/create_offer_user", to: "offers#create_offer_user", as: "create_offer_user"
  post "offers/change_status" => "offers#change_status"
  post "users/create_user", to: "users#create_user", as: "create_user"
end

app/models/offer.rb
class Offer < ActiveRecord::Base
	after_initialize :init

	scope :within_range, lambda { where("created_at <= ?", Date.today + 30) }
	# Validations
	validates :service_start_date, presence: true 
	validates :service_finish_date, presence: true 
	validates :offer_start_date, presence: true 
	validates :offer_finish_date, presence: true
	# relationship
	has_many :users, :through => :offer_users
	has_many :offer_users, :dependent => :destroy
	has_many :comments
	# default for will_paginate
  	self.per_page = 10

  	def init
		self.status  ||= 1
	end

	# search dates

	ransacker :service_start_date do
  	Arel::Nodes::SqlLiteral.new("date(offers.service_start_date)")
	end

	ransacker :service_finish_date do
  	Arel::Nodes::SqlLiteral.new("date(offers.service_finish_date)")
	end

	ransacker :offer_finish_date do
  	Arel::Nodes::SqlLiteral.new("date(offers.offer_finish_date)")
	end

	ransacker :offer_start_date do
  	Arel::Nodes::SqlLiteral.new("date(offers.offer_start_date)")
	end

	def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |offer|
        csv << offer.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

 # GET /Offers
  # GET /Offers.json
  def index
    @offer = Offer.new()
    @product = Product.new()
    @location = Location.new()
    @measure = Measure.new()
    
    if current_user.rol == "admin" or current_user.rol == "supervicer" 
      @search = Offer.within_range.ransack(params[:q])
      @offers = @search.result.order(created_at: :desc).page(params[:page])
    elsif current_user.rol == "providers"
      @search = Offer.ransack(params[:q])
      @offers = Offer.where('offers.status = ?', '1').order(created_at: :desc).page(params[:page])
    end
    respond_to do |format|
        format.html
        format.js
        format.csv { send_data @offers.to_csv }
        format.xls { send_data @offers.to_csv(col_sep: "\t") }
    end
  end

  # GET /Offers/1
  # GET /Offers/1.json
  def show
    @comment = Comment.new
    @search = OfferUser.search_offer(params[:id]).ransack(params[:q])
    if params[:q]
      @offer_users = @search.result.order(price: :desc).page(params[:page])
    else
      @offer_users = OfferUser.where(offer_id: params[:id]).order(price: :desc).page(params[:page]) 
    end
    @offer_user = OfferUser.find_by_offer_id_and_user_id(params[:id], current_user.id)
  end

  def download
    @offer_users = OfferUser.where(offer_id: params[:offer_id]).order(price: :desc).page(params[:page]) 
    respond_to do |format|
      format.html
      format.xls { send_data @offer_users.to_csv(col_sep: "\t") }
    end
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        flash[:notice] = 'Se ha creado su nueva oferta'
        format.html { redirect_to @offer }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        flash[:notice] = 'Se ha modificado su oferta'
        format.html { redirect_to @offer }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_status 
    @offer = Offer.find(params[:id]) 
    val = @offer.status == 1 ? 2 : 1 
    @offer.update_attribute(:status, val)  
    respond_to do |format|
      if @offer.status == 1
        format.html { redirect_to @offer, notice: 'Se ha Activado su oferta' }
      else @offer.status == 2
        format.html { redirect_to @offer, notice: 'Se ha Desactivado su oferta' }
      end
    end    
  end

  def extend
    @offer = Offer.find(params[:id])
    service_finish_date = params[:offer][:service_finish_date]
    offer_finish_date = params[:offer][:offer_finish_date]
    respond_to do |format|
      if @offer.update(:service_finish_date => service_finish_date , :offer_finish_date => offer_finish_date)
        format.html { redirect_to @offer, notice: 'Se ha extendido su oferta' }
      end
    end  
  end

  # POST /Offer_User
  # POST /Offer_User.json
  def create_offer_user
    if OfferUser.exists?(offer_id: params[:offer_user][:offer_id], user_id: params[:offer_user][:user_id])
       @offer_user = OfferUser.find_by_offer_id_and_user_id(params[:offer_user][:offer_id],params[:offer_user][:user_id])
       @offer_user.update(quantity: params[:offer_user][:quantity], price: params[:offer_user][:price])
    else
      @offer_user = OfferUser.new(quantity: params[:offer_user][:quantity], price: params[:offer_user][:price], offer_id: params[:offer_user][:offer_id], user_id: params[:offer_user][:user_id])
    end
    respond_to do |format|
      if @offer_user.save
        flash[:notice] = 'Su oferta ha sido creada exitosamente'
        format.html { redirect_to root_path}
        format.js   {}
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
        format.js   {}
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Su oferta ha sido eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:product, :origins, :destination, :volumen, :price, :container, :general_load, :liquid_load, :load_compensation, :offert_type, :unit, :observation, :status, :service_start_date, :offer_finish_date, :offer_start_date, :service_finish_date)
    end
end

app/views/offers/_extend.html.slim
#myModal.modal.fade[tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"]
  .modal-dialog
    .modal-content
      .modal-header
        button.close[type="button" data-dismiss="modal" aria-label="Close"]
          span[aria-hidden="true"]
            | ×
        h4#myModalLabel.modal-title
          | Extender Oferta
      .modal-body
        = form_for :offer , url: extend_path(id: @offer.id), :id => @offer.id  do |f|
          label[for="product_Referencia"]
            | Fecha de Servicio de oferta
          = f.text_field :service_finish_date, :class =>"date form-control"
          label[for="product_Nombre"]
            | Fecha de oferta
          = f.text_field :offer_finish_date, :class =>"date form-control"
          br
          = f.submit :class =>"btn btn-primary btn-block"

app/views/offers/_filters.html.slim
#filter-panel.collapse.filter-panel
  .panel.panel-default
    .panel-body
      = search_form_for @search do |f|
        .col-md-12
          label
            = t('.offert_type')
          = f.select :offert_type_cont, [["Tipo Oferta 1", "oferta1"],["Tipo Oferta 2", "oferta2"]], {prompt: "Seleccione Tipo Oferta"}, {class: "form-control"}
        .col-md-3
          label
            = t('.product')
          = f.collection_select :product_cont, Product.all, :name, :name, {prompt: " "}, {class: "form-control"}
        .col-md-3
          label
            = t('.origins')
          = f.collection_select :origins_cont, Location.all, :location, :location, {prompt: " "}, {class: "form-control"}
        .col-md-3
          label
            = t('.destination')
          = f.collection_select :destination_cont, Location.all, :location, :location, {prompt: " "}, {class: "form-control"}
        .col-md-3
          label
            = t('.volumen')
          = f.search_field(:volumen_cont, class: 'form-control')
        .col-md-3
          label
            = t('.price')
          = f.search_field(:price_cont, class: 'form-control')
        .col-md-3
          label
            = t('.service_start_date')
          = f.search_field(:service_start_date_cont, class: 'form-control date')
        .col-md-3
          label
            = t('.service_finish_date')
          = f.search_field(:service_finish_date_cont, class: 'form-control date')
        .col-md-3
          label
            = t('.offer_start_date')
          = f.search_field(:offer_start_date_cont, class: 'form-control date')
        .col-md-3
          label
            = t('.offer_finish_date')
          = f.search_field(:offer_finish_date_cont, class: 'form-control date')
        .col-md-3
          br
          = f.submit :class =>"btn btn btn-primary btn-block"
        .col-md-3
          br
          = link_to t('.clear'), request.path, class:"btn btn-danger btn_white btn-block"

.row 
  .col-md-6
    button.btn.btn-primary[type="button" data-toggle="collapse" data-target="#filter-panel" style="margin-bottom: 10px;"]
      span.fa.fa-filter
      = t('.filters')
  - if current_user.rol == "admin" or current_user.rol == "supervicer" 
    .col-md-6
      .pull-right
        = link_to new_offer_path, :class => 'btn btn-primary'
          span.fa.fa-plus-circle

app/views/offers/_form.html.slim
div
  = form_for @offer do |f|
    .form-group
      label
        | Tipo de Oferta
      = f.select :offert_type, [["Tipo Oferta 1", "oferta1"],["Tipo Oferta 2", "oferta2"]], {prompt: "Seleccione Tipo Oferta"}, {class: "form-control"}
    .form-group
      label
        | Carga Compensatoría
      = f.check_box :load_compensation
    .row
      .col-xs-4.col-sm-4.col-md-4
        .form-group
          label
            | Tipo de Producto
          =  f.collection_select :product, Product.all, :name, :name, {prompt: " "}, {class: "form-control"}
      .col-xs-4.col-sm-4.col-md-4
        .form-group
          label
            | Origen
          =  f.collection_select :origins, Location.all, :location, :location, {prompt: " "}, {class: "form-control"}
      .col-xs-4.col-sm-4.col-md-4
        .form-group
          label
            | Destino
          =  f.collection_select :destination, Location.all, :location, :location, {prompt: " "}, {class: "form-control"}
    .row
      .col-xs-6.col-sm-6.col-md-6
        .form-group
          label
            | Und. Cotización
          =  f.collection_select :unit, Measure.all, :unit, :unit, {prompt: " "}, {class: "form-control"}
      .col-xs-6.col-sm-6.col-md-6
        .form-group
          label
            | Volumen Demandado
          = f.text_field :volumen, class:"form-control"
          span#errmsg
    .form-group
      = f.label :price, :id => "price"
      = f.text_field :price, class:"form-control"
      span#errmsg1
    .row
      .col-xs-6.col-sm-6.col-md-6
        .form-group
          label
            | Fecha Inicio Servicio
          = f.text_field :service_start_date,class:"form-control date"
      .col-xs-6.col-sm-6.col-md-6
        .form-group
          label
            | Fecha Fin Servicio 
          = f.text_field :service_finish_date, class:"form-control date"
    .row
      .col-xs-6.col-sm-6.col-md-6
        .form-group
          label
            | Fecha Inicio Oferta 
          = f.text_field :offer_start_date, class:"form-control date"
      .col-xs-6.col-sm-6.col-md-6
        .form-group
          label
            | Fecha Fin Oferta 
          = f.text_field :offer_finish_date, class:"form-control date"
    .row
      .col-xs-4.col-sm-4.col-md-4
        .form-group
          label
            | Contenedor
          = f.check_box :container, :class=>"group_checked"
      .col-xs-4.col-sm-4.col-md-4
        .form-group
          label
            | Carga General
          = f.check_box :general_load, :class=>"group_checked"
      .col-xs-4.col-sm-4.col-md-4
        .form-group
          label
            | Carga Liquida
          = f.check_box :liquid_load, :class=>"group_checked"
    .form-group
      label
        | Observaciones
      br
      = f.text_area :observation, :rows => "4" , :cols => "2" , :class => "textare_w100"
    = f.submit :class =>"btn btn-primary btn-block"

app/views/offers/_modal.html.slim
|  <div class="modal fade" id="myModal
= offer.id
| " tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> 
.modal-dialog
  .modal-content
    .modal-header
      button.close[type="button" data-dismiss="modal" aria-label="Close"]
        span[aria-hidden="true"]
          | ×
      |  <h4 class="modal-title" id="myModal
      = offer.id
      | -label">
      = t('.observations')
    .modal-body
      = offer.observation

app/views/offers/_offer_user.html.slim
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        h3
          | ¿Desea inscribirse en esta oferta?
      .panel-body
        .row
          .col-xs-6
            .well
              = form_for :offer_user, url: url_for(:controller => :offers, :action => :create_offer_user ), html: { method: :post , name: "offer_user", :onsubmit => "return validateForm()" } do |f|
                = f.label :Cantidad
                = f.number_field :quantity, :class =>"form-control", :max => "#{@offer.volumen}"
                = f.label :Precio
                = f.text_field :price, :class =>"form-control"
                = f.hidden_field :offer_id, :value => "#{params[:id]}"
                = f.hidden_field :user_id, :value => "#{current_user.id}"
                br
                = f.submit :class =>"btn btn-primary btn-block",disabled: @offer_user_find_by_id
          .col-xs-6
            .well
             = render :partial => "comments/form"

            

app/views/offers/_offer_users.html.slim
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        h3
          | Clasificación de ofertantes
        / .row
        /   .col-md-12.pull-right
        /     -if current_user.rol == "admin"
        /       = link_to "Descargar Excel", offers_download_path(format: "xls", :id => params[:id]), :class => "btn btn-success "
      .panel-body
        .row
          .col-md-12
            table#dev-table.table.table-hover
              thead
                tr
                  th
                    = t('.id')
                  th
                    = t('.name')
                  th
                    = t('.carrier')
                  th
                    = sort_link @search, :volumen, t('.volumen')
                  th
                    = sort_link @search, :price, t('.price')
                  th
                    = t('.cell_phone')
                  th
                    = t('.landline')
              tbody
                - @offer_users.each do |offer_user|
                  tr
                    td
                      = offer_user.id
                    td
                      = offer_user.user.name
                    td
                      = offer_user.user.carrier
                    td
                      = number_with_delimiter(offer_user.quantity, :delimiter => '.') 
                    td
                      = " $#{number_with_delimiter(offer_user.price, :delimiter => '.')}"
                    td
                      = offer_user.user.landline
                    td
                      = offer_user.user.cell_phone
            = will_paginate @offer_users, :locals => { :offer_users => @offer_users }, renderer: BootstrapPagination::Rails

app/views/offers/_shortcuts.html.erb
<div class="row">
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-users shortcuts"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><%= User.all.count%></div>
						<div><%= t('.provider')%></div>
					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<i class="pull-left"><a href="<%= new_user_path%>"><%= t('.add_provider')%></a></i>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-cubes shortcuts"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><%= Measure.all.count%></div>
						<div><%= t('.measures')%></div>
					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<i class="pull-left"><a href="#" data-toggle="modal" data-target="#myModalmeasure"><%= t('.add_measure')%></a></i>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-bookmark shortcuts"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><%= Product.all.count%></div>
						<div><%= t('.products')%></div>
					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<i class="pull-left"><a href="#" data-toggle="modal" data-target="#myModalProducto"><%= t('.add_product')%></a></i>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-location-arrow shortcuts"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><%= Location.all.count%></div>
						<div><%= t('.locations')%></div>
					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<i class="pull-left"><a href="#" data-toggle="modal" data-target="#myModalLocation"><%= t('.add_location')%></a></i>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
</div>

app/views/offers/create.js.erb
	<%if @offer.errors.any? %>
	$('.errors').append('<div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> <%= @offer.errors.full_messages.to_sentence%></div>');
	<%else%>
	$('.errors').append('<div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong> Se ha creado su nueva ubicación </strong></div>');
	$('#offer_volumen').val(" ")
	$('#offer_service_start_date').val(" ")
	$('#offer_service_finish_date').val(" ")
	$('#offer_offer_finish_date').val(" ")
	$('#offer_offer_start_date').val(" ")
	$('#offer_price').val(" ")
	$('#offer_observations').val(" ")
	$('#offer_load_compensation').prop( "checked", false );
	$('#offer_container').prop( "checked", false );
	$('#offer_general_load').prop( "checked", false );
	$('#offer_liquid_load').prop( "checked", false );
	<%end%

app/views/offers/edit.html.slim
- model_class = Offer
.page-header
  ol.breadcrumb
    li.active
      i.fa.fa-truck style="margin-right: 10px;"
      | MODIFICAR OFERTA
= render :partial => "form"

app/views/offers/index.html.slim
- model_class = Offer
- if current_user.rol == "admin" or current_user.rol == "supervicer" 
  = render(partial: 'shortcuts')
.page-header
  ol.breadcrumb
    li.active
      i.fa.fa-truck style="margin-right: 10px;"
      | LISTADO DE OFERTAS
= render(partial: 'offers/filters')
-if current_user.rol == "admin"
  = link_to "Descargar Excel", offers_path(format: "xls"), :class => "btn btn-success"
  br
  br
table.table.table-striped.table-hover.table-bordered
  thead
    tr
      th= sort_link @search, :id, t('.id')
      th= sort_link @search, :product, t('.product')
      th= sort_link @search, :origins, t('.origins')
      th= sort_link @search, :destination, t('.destination')
      th= sort_link @search, :volumen,t('.volumen')
      th= sort_link @search, :price,t('.price')
      th= sort_link @search, :service_start_date, t('.service_start_date')
      th= sort_link @search, :service_finish_date, t('.service_finish_date')
      th= sort_link @search, :offer_start_date, t('.offer_start_date')
      th= sort_link @search, :offer_finish_date, t('.offer_finish_date')
      th
      - if current_user.rol == "admin" or current_user.rol == "supervicer" 
        th=t '.actions', :default => t("helpers.actions")
  tbody
    - @offers.each do |offer|
      tr class=('danger' if offer.status == 2)
        td.w120
          - if current_user.rol == "admin"
            span.label.label-success
              = user_count(offer)
          = offer.id
        td= offer.product
        td= offer.origins
        td= offer.destination
        td.w900= "#{number_with_delimiter(offer.volumen, :delimiter => '.')} #{offer.unit}"
        td.w120= number_to_currency_br(offer.price)
        td= offer.service_start_date
        td= offer.service_finish_date 
        td= offer.offer_start_date
        td= offer.offer_finish_date
        td= link_to "ver oferta", offer_path(offer)
        - if current_user.rol == "admin" or current_user.rol == "supervicer" 
          td.w120
            = link_to edit_offer_path(offer)
                  span.fa.fa-pencil
            '
            = link_to offer, data: {:confirm => t('.delete')}, :method => :delete do
                span.fa.fa-trash-o

            button.btn.btn-link.eye data-toggle="modal" data-target="#myModal#{offer.id}" 
                  span.fa.fa-eye
            = render(partial: 'offers/modal',locals: { offer: offer })

= will_paginate @offers, :locals => { :offers => @offers }, renderer: BootstrapPagination::Rails

= render(partial: 'products/modal')
= render(partial: 'measures/modal')
= render(partial: 'locations/modal')

app/views/offers/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Productos</Data></Cell>
        <Cell><Data ss:Type="String">Origenes</Data></Cell>
        <Cell><Data ss:Type="String">Destino</Data></Cell>
        <Cell><Data ss:Type="String">Volumen</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
        <Cell><Data ss:Type="String">Incio Servicio</Data></Cell>
        <Cell><Data ss:Type="String">Fin Servicio</Data></Cell>
        <Cell><Data ss:Type="String">Incio Oferta</Data></Cell>
        <Cell><Data ss:Type="String">Fin Oferta</Data></Cell>
      </Row>
    <% @offers.each do |offer| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= offer.id %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= offer.product %></Data></Cell>
        <Cell><Data ss:Type="String"><%= offer.origins %></Data></Cell>
        <Cell><Data ss:Type="String"><%= offer.destination %></Data></Cell>
        <Cell><Data ss:Type="String"><%= offer.volumen %></Data></Cell>
        <Cell><Data ss:Type="String"><%= number_to_currency_br(offer.price) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= offer.service_start_date.strftime("%d-%m-%Y") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= offer.service_finish_date.strftime("%d-%m-%Y") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= offer.offer_finish_date.strftime("%d-%m-%Y") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= offer.offer_start_date.strftime("%d-%m-%Y") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= offer.offer_finish_date.strftime("%d-%m-%Y") %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/offers/new.html.slim
- model_class = Offer
.page-header
  ol.breadcrumb
    li.active
      i.fa.fa-truck style="margin-right: 10px;"
      | AGREGAR OFERTA
= render :partial => "form"

app/views/offers/show.html.slim
javascript:
  date = "#{@offer.offer_finish_date }";
  
coffee:
  $(document).ready ->
    offer_finish_date = date
    $ ->
      untilDay = new Date(offer_finish_date)
      untilDay.setHours(untilDay.getHours() + 5)
      $('.defaultCountdown').countdown until: untilDay
      return

.page-header
  ol.breadcrumb
    li.active
      i.fa.fa-truck style="margin-right: 10px;"
      = t('.head')
.row
  .col-xs-12
  - if @offer.offer_finish_date < Time.now
      - @offer.update(:status => 2)
  - else
      .defaultCountdown
      br
      br
hr
- if current_user.rol == "admin" or current_user.rol == "supervicer"
  = render(partial: 'offers/offer_users')
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        h3
          strong
            |  Código de oferta
            = "  #{@offer.id}"
      .panel-body
        - if current_user.rol == "admin" or current_user.rol == "supervicer"
          .row
            .col-lg-3
              p
                a.btn.btn-outlined.btn-block.btn-success[href="#" data-toggle="modal" data-target="#myModal"]
                  = t('.extend')
            .col-lg-3
              p
                = link_to(t('.edit'), edit_offer_path(@offer), html_options = {:class => "btn btn-outlined btn-block btn-info"})
            .col-lg-3
              = button_to statuts(@offer.status), { :controller => "offers", :action => "change_status", :id => @offer.id, :method => :put}, html_options = {:class => "btn btn-outlined btn-block  btn_white btn-warning"}
            .col-lg-3
              p
                = link_to(t('.delete'), @offer, html_options = {:class => "btn btn_white btn-outlined btn-block btn-danger", data: {:confirm => t('.data_delete')}, :method => :delete} )
          hr
        .row
          .row
            .col-lg-12
              .col-lg-3
                span.bold
                  = t('.product')
                p
                  = @offer.product
              .col-lg-3
                span.bold
                  = t('.volumen')
                p
                  = "#{number_with_delimiter(@offer.volumen, :delimiter => '.')} #{@offer.unit}"
              .col-lg-3
                span.bold
                  = t('.origins')
                p
                  = @offer.origins
              .col-lg-3
                span.bold
                  = t('.destination')
                p
                  = @offer.destination
            .col-lg-12
              .col-lg-3
                span.bold
                  = t('.type')
                - if @offer.liquid_load
                  =  t('.liquid_load')
                - elsif @offer.general_load
                  =  t('.general_load')
                - elsif @offer.container
                  =  t('.container')
              .col-lg-3
                span.bold
                - if @offer.load_compensation
                  =  t('.load_compensation')
            .col-lg-12
              br
              .col-lg-3
                span.bold
                  = t('.offer_start_date')
                p
                  = @offer.offer_start_date
              .col-lg-3
                span.bold
                  = t('.offer_finish_date')
                p
                  = @offer.offer_finish_date
              .col-lg-3
                span.bold
                  = t('.service_start_date')
                p
                  = @offer.service_start_date
              .col-lg-3
                span.bold
                  = t('.service_finish_date')
                p
                  = @offer.service_finish_date
              br
          .col-lg-12
            span.bold
              = t('.observations')
            p
              = @offer.observation
- if current_user.rol == "admin" or current_user.rol == "supervicer"
  = render(partial: 'offers/extend')
- else
  = render(partial: 'offers/offer_user')