config/routes.rb
Rails.application.routes.draw do
  root 'offers#index'
  resources :offers
  resources :measures
  resources :comments
  resources :locations
  resources :products
  devise_for :users
  resources :users, :except => [:edit]
  match 'comments/send_mail', to: 'comments#send_mail', via: 'post'
  get  "offers/download", to: "offers#download"
  post  "offers/extend", to: "offers#extend", as: "extend"
  post "offers/create_offer_user", to: "offers#create_offer_user", as: "create_offer_user"
  post "offers/change_status" => "offers#change_status"
  post "users/create_user", to: "users#create_user", as: "create_user"
end

app/models/product.rb
class Product < ActiveRecord::Base
	# Validations
	validates :name, presence: true 
	validates :ref, presence: true 

	self.per_page = 10
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @search = Product.ransack(params[:q])
    @products = @search.result.page(params[:page])
    @product = Product.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        flash[:notice] = 'Se ha creado su nuevo producto'
        format.html { redirect_to @product }
        format.js   {}
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.js   {}
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Offers/1
  # PATCH/PUT /Offers/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        flash[:notice] = 'La producto ha sido actualizado'
        format.html { redirect_to @product }
        format.json { render :show, status: :ok, location: @product }
        format.js   { js_redirect_to(products_path)}
      else
        format.html { render :edit }
        format.js   {}
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = 'El producto ha sido eliminado'
    redirect_to products_url
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :ref)
    end
end

app/views/products/_filters.html.slim
#filter-panel.collapse.filter-panel
  .panel.panel-default
    .panel-body
      = search_form_for @search do |f|
        .col-md-3
          label
            = t('.name')
          = f.search_field(:name_cont, class: 'form-control')
        .col-md-3
          label
            = t('.ref')
          = f.search_field(:ref_cont, class: 'form-control')
        .col-md-3
          br
          = f.submit :class =>"btn btn btn-primary btn-block"
        .col-md-3
          br
          = link_to t('.clear'), request.path, class:"btn btn-danger btn_white btn-block"

.row 
  .col-md-6
    button.btn.btn-primary[type="button" data-toggle="collapse" data-target="#filter-panel" style="margin-bottom: 10px;"]
      span.fa.fa-filter
      = t('.filters')
  .col-md-6
    .pull-right
      = link_to new_product_path, :class => 'btn btn-primary'
        span.fa.fa-plus-circle

app/views/products/_form.html.slim
.errors
= form_for @product,  remote: true do |f|
    = f.label :Referencia
    = f.text_field :ref, :class =>"form-control"
    br
    = f.label :Nombre
    = f.text_field :name, :class =>"form-control"
    br
    =f.submit :class =>"btn btn-primary btn-block"

app/views/products/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModalProducto" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Agregar Producto</h4>
      </div>
      <div class="modal-body">
        <div class="errors"></div>
        <%= render 'products/form'%>
      </div>
    </div>
  </div>
</div>

app/views/products/create.js.erb
<%if @product.errors.any? %>
	$('.errors').append('<div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> <%= @product.errors.full_messages.to_sentence%></div>');
<%else%>
	$('.errors').append('<div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong> Se ha creado su nuevo producto </strong></div>');
	$('#product_ref').val(" ")
	$('#product_name').val(" ")
<%end%>

app/views/products/edit.html.slim
- model_class = Product
.page-header
  ol.breadcrumb
    li.active
      i.fa.fa-bookmark style="margin-right: 10px;"
      | MODIFICAR PRODUCTO
= render :partial => "form"

app/views/products/index.html.slim
- model_class = Product
.page-header
  ol.breadcrumb
    li.active
      i.fa.fa-location-arrow style="margin-right: 10px;"
      | LISTADO DE PRODUCTOS
= render(partial: 'products/filters')
br
br

table.table.table-striped.table-hover.table-bordered
  thead
    tr
      th=  sort_link @search, :id, "#"
      th=  sort_link @search, :name, t('.name')
      th=  sort_link @search, :ref, t('.ref')
      th=t '.actions', :default => t("helpers.actions")
      
  tbody
    - @products.each do |product|
      tr
        td= product.id
        td= product.name
        td= product.ref
        td
          = link_to edit_product_path(product)
              span.fa.fa-pencil
          =  link_to product, data: {:confirm => "Eliminar producto"}, :method => :delete do
              span.fa.fa-trash-o.delete

= will_paginate @products, :locals => { :products => @products }, renderer: BootstrapPagination::Rails

app/views/products/new.html.slim
- model_class = Product
.page-header
  ol.breadcrumb
    li.active
      i.fa.fa-bookmark style="margin-right: 10px;"
      | AGREGAR PRODUCTO
= render :partial => "form"